import Head from 'next/head';
import {useEffect} from 'react';
import Script from 'next/script';
import About from '../components/About/About';
import Form from '../components/Contact/Form';
import Hero from '../components/Hero/Hero';
import Projects from '../components/Projects/Projects';
import Skills from '../components/Skills/Skills';
import useStateValue from '../store/useContext';
import ReactGA from 'react-ga';

const Home = () => {
	useEffect(() => {
		ReactGA.initialize('372632070');
		ReactGA.pageview(window.location.pathname + window.location.search);
	}, []);

	const [state] = useStateValue();
	const {isDark} = state.theme;

	return (
		<div className={`md:snap-y-X md:overflow-scroll md:scroll-smooth-X  md:snap-mandatory-X h-full md:h-full  ${isDark ? 'bg-black' : 'bg-white'} `}>
			<Head>
				<title>Omid Heidari</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Script async src={`https://www.googletagmanager.com/gtag/js?id=G-8JCQBPR9CP`} strategy='afterInteractive' />
			<Script id='124dfs-analytics' strategy='afterInteractive'>
				{`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-8JCQBPR9CP');
        `}
			</Script>

			<div>
				<Hero />
				<About />
				<Skills />
				<Projects />
				<Form />
			</div>
		</div>
	);
};

export default Home;
