import Head from 'next/head';
import About from '../components/About/About';
import Form from '../components/Contact/Form';
import Hero from '../components/Hero/Hero';
import Projects from '../components/Projects/Projects';
import Skills from '../components/Skills/Skills';
import useStateValue from '../store/useContext';

const Home = () => {
	const [state] = useStateValue();
	const {isDark} = state.theme;
	return (
		<div
			className={`lg:snap-y lg:overflow-scroll lg:scroll-smooth  lg:snap-mandatory h-screen  ${
				isDark ? 'bg-black' : 'bg-white'
			} `}
		>
			<Head>
				<title>iDevOh</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Hero />
			<About />
			<Skills />
			<Projects />
			<Form />
		</div>
	);
};

export default Home;
